framework:
  workflows:
    purchase_request_flow:
      type: 'state_machine'
      marking_store:
        type: 'method'
        property: 'status'
      supports:
        - App\Entity\PurchaseRequest
      initial_marking: draft
      places:
        - draft
        - pending
        - approved
        - rejected
      transitions:
        submit:
          from: [draft, rejected]
          to: pending
        approve:
          from: pending
          to: approved
        reject:
          from: pending
          to: rejected
